package:
  name: rabpro
  version: "0.2"

source:
  path: ..

requirements:
  build:
    - python
    - setuptools
  host:
    - python
    - gdal
  run:
    - python
    - gdal
    - numpy
    - geopandas=0.7.0
    - scikit-image
    - opencv
    - matplotlib
    - pyproj
    - shapely
    - rivgraph=0.3
    - requests
    - appdirs
    - earthengine-api

test:
  imports:
    - rabpro

about:
  home: https://github.com/jonschwenk/rabpro
