name: gee_catalog_parser
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'

      # TODO: Add pip cache and requirements.txt
      
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests earthengine-api

      - name: set up credentials
        run: |
          mkdir -p "$HOME/.config/earthengine"
          echo "$EARTH_ENGINE_KEY" > "$HOME/.config/earthengine/credentials"
        env:
          EARTH_ENGINE_KEY: ${{ secrets.EARTH_ENGINE_SECRET }}

      - name: run web parser
        run: python3 ./Data/webparser.py

      - name: commit json file
        run: |
          git config --global user.name 'GitHub Action'
          git config --local user.email "action@github.com"
          git add -A
          git commit -m "Updated GEE datasets ($(date +"%Y-%m-%d"))" -a

      - name: push json file
        run: git push
        